export const HOTEL_LIST_REQUEST = 'HOTEL_LIST_REQUEST';
export const HOTEL_LIST_SUCCESS = 'HOTEL_LIST_SUCCESS';
export const HOTEL_LIST_FAIL = 'HOTEL_LIST_FAIL';

export const TOP_HOTEL_LIST_REQUEST = 'TOP_HOTEL_LIST_REQUEST';
export const TOP_HOTEL_LIST_SUCCESS = 'TOP_HOTEL_LIST_SUCCESS';
export const TOP_HOTEL_LIST_FAIL = 'TOP_HOTEL_LIST_FAIL';

export const HOTEL_BY_ID_REQUEST = 'HOTEL_BY_ID_REQUEST';
export const HOTEL_BY_ID_SUCCESS = 'HOTEL_BY_ID_SUCCESS';
export const HOTEL_BY_ID_FAIL = 'HOTEL_BY_ID_FAIL';
