export const HOTEL_LIST_REQUEST = 'HOTEL_LIST_REQUEST';
export const HOTEL_LIST_SUCCESS = 'HOTEL_LIST_SUCCESS';
export const HOTEL_LIST_FAIL = 'HOTEL_LIST_FAIL';

export const TOP_HOTEL_LIST_REQUEST = 'TOP_HOTEL_LIST_REQUEST';
export const TOP_HOTEL_LIST_SUCCESS = 'TOP_HOTEL_LIST_SUCCESS';
export const TOP_HOTEL_LIST_FAIL = 'TOP_HOTEL_LIST_FAIL';

export const HOTEL_BY_ID_REQUEST = 'HOTEL_BY_ID_REQUEST';
export const HOTEL_BY_ID_SUCCESS = 'HOTEL_BY_ID_SUCCESS';
export const HOTEL_BY_ID_FAIL = 'HOTEL_BY_ID_FAIL';

export const HOTEL_CREATE_REQUEST = 'HOTEL_CREATE_REQUEST';
export const HOTEL_CREATE_SUCCESS = 'HOTEL_CREATE_SUCCESS';
export const HOTEL_CREATE_FAIL = 'HOTEL_CREATE_FAIL';

export const HOTEL_UPDATE_REQUEST = 'HOTEL_UPDATE_REQUEST';
export const HOTEL_UPDATE_SUCCESS = 'HOTEL_UPDATE_SUCCESS';
export const HOTEL_UPDATE_FAIL = 'HOTEL_UPDATE_FAIL';

export const GALLARY_CREATE_REQUEST = 'GALLARY_CREATE_REQUEST';
export const GALLARY_CREATE_SUCCESS = 'GALLARY_CREATE_SUCCESS';
export const GALLARY_CREATE_FAIL = 'GALLARY_CREATE_FAIL';

export const GALLARY_UPDATE_REQUEST = 'GALLARY_UPDATE_REQUEST';
export const GALLARY_UPDATE_SUCCESS = 'GALLARY_UPDATE_SUCCESS';
export const GALLARY_UPDATE_FAIL = 'GALLARY_UPDATE_FAIL';
